import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'ticket_form_models.dart';

/// ------------------------------------------------------------
/// VIOLATOR DETAILS
/// ------------------------------------------------------------
class ViolatorDetailsSection extends StatelessWidget {
  final TextEditingController violatorName;
  final TextEditingController driversLicense;
  final TextEditingController plateNo;

  const ViolatorDetailsSection({
    super.key,
    required this.violatorName,
    required this.driversLicense,
    required this.plateNo,
  });

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      title: 'Violator Details',
      children: [
        TextFormField(
          controller: violatorName,
          decoration: const InputDecoration(labelText: 'Violator Name'),
          textCapitalization: TextCapitalization.words,
          validator: (value) =>
              value == null || value.trim().isEmpty ? 'Required' : null,
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: driversLicense,
          decoration: const InputDecoration(labelText: 'Driver\'s License No.'),
          validator: (value) =>
              value == null || value.trim().isEmpty ? 'Required' : null,
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: plateNo,
          decoration: const InputDecoration(labelText: 'Plate No. (optional)'),
        ),
        // 👇 No more Control No field – it will be generated by backend
      ],
    );
  }
}


/// ------------------------------------------------------------
/// VIOLATIONS (multi-select)
/// ------------------------------------------------------------
class ViolationSection extends StatelessWidget {
  final List<String> violationTypes;
  final String? selectedType;

  final List<ViolationOption> violations;
  final List<ViolationOption> selectedViolations;

  final bool loadingViolations;
  final String? violationsError;

  final TextEditingController fineController;

  final ValueChanged<String> onTypeChanged;
  final void Function(ViolationOption, bool) onToggleViolation;

  const ViolationSection({
    super.key,
    required this.violationTypes,
    required this.selectedType,
    required this.violations,
    required this.selectedViolations,
    required this.loadingViolations,
    required this.violationsError,
    required this.fineController,
    required this.onTypeChanged,
    required this.onToggleViolation,
  });

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      title: 'Violations',
      children: [
        // 🔹 Type filter
        DropdownButtonFormField<String>(
          value: selectedType,
          decoration: const InputDecoration(labelText: 'Violation Type'),
          items: violationTypes
              .map((t) => DropdownMenuItem<String>(value: t, child: Text(t)))
              .toList(),
          onChanged: (value) {
            if (value == null) return;
            onTypeChanged(value);
          },
          validator: (value) =>
              value == null || value.isEmpty ? 'Required' : null,
        ),
        const SizedBox(height: 12),

        if (loadingViolations) ...[
          const LinearProgressIndicator(),
          const SizedBox(height: 8),
        ] else ...[
          // 🔹 List of checkboxes for each violation
          if (violations.isNotEmpty)
            Column(
              children: violations.map((v) {
                final checked = selectedViolations.any((e) => e.id == v.id);
                return CheckboxListTile(
                  value: checked,
                  onChanged: (val) => onToggleViolation(v, val ?? false),
                  dense: true,
                  title: Text(v.name),
                  subtitle: Text(
                    'Fine: ₱ ${v.fine.toStringAsFixed(2)}',
                    style: Theme.of(
                      context,
                    ).textTheme.bodySmall?.copyWith(color: Colors.grey[600]),
                  ),
                );
              }).toList(),
            )
          else
            const Text(
              'No violations found for this type.',
              style: TextStyle(fontSize: 12),
            ),
        ],

        const SizedBox(height: 12),

        // 🔹 Total fine field (read-only)
        TextFormField(
          controller: fineController,
          readOnly: true,
          keyboardType: const TextInputType.numberWithOptions(decimal: true),
          inputFormatters: [
            FilteringTextInputFormatter.allow(RegExp(r'[0-9.]')),
          ],
          decoration: const InputDecoration(
            labelText: 'Total Fine (₱)',
            helperText: 'Sum of all selected violations',
          ),
          validator: (_) => selectedViolations.isEmpty
              ? 'Select at least one violation'
              : null,
        ),

        if (violationsError != null) ...[
          const SizedBox(height: 8),
          Text(
            violationsError!,
            style: TextStyle(
              color: Theme.of(context).colorScheme.error,
              fontSize: 12,
            ),
          ),
        ],
      ],
    );
  }
}

/// ------------------------------------------------------------
/// LOCATION
/// ------------------------------------------------------------
class LocationSection extends StatelessWidget {
  final String chokepoint;

  const LocationSection({super.key, required this.chokepoint});

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      title: 'Location',
      children: [
        TextFormField(
          enabled: false,
          initialValue: chokepoint,
          decoration: const InputDecoration(
            labelText: 'Place of Apprehension (chokepoint)',
            helperText: 'Auto-filled from active shift',
          ),
        ),
      ],
    );
  }
}

/// ------------------------------------------------------------
/// SHARED CARD WIDGET
/// ------------------------------------------------------------
class SectionCard extends StatelessWidget {
  final String title;
  final List<Widget> children;

  const SectionCard({super.key, required this.title, required this.children});

  @override
  Widget build(BuildContext context) {
    final titleStyle = Theme.of(
      context,
    ).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w800);

    return Card(
      child: Padding(
        padding: const EdgeInsets.fromLTRB(16, 14, 16, 16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(title, style: titleStyle),
            const SizedBox(height: 12),
            ...children,
          ],
        ),
      ),
    );
  }
}
